TWEAK_NAME = sandcastleclient
sandcastleclient_LOGOS_FILES = Tweak.xm
sandcastleclient_CFLAGS=-I.. -I.
sandcastleclient_PRIVATE_FRAMEWORKS = AppSupport


include ../framework/makefiles/common.mk
include ../framework/makefiles/tweak.mk

